- src/plugin/NetEase/normalize.py
> 歌词时间为 [00:13.0] 导致崩溃

- src/widgets/lyric_widget.py
> 暂时修复翻译歌词比原歌词短导致的崩溃

- src/top_widget.py
- src/widgets/lyric_widget.py
> minor bug fix

- src/interfaces.py
> fix: set music to favorite doesnot cause play list reloading

- src/base/player.py
出现网络故障后，三秒后重试播放。
我这网络环境挺恶劣的..  0_0
> Retry playing after 3 seconds if network error happened

- src/base/player.py
出错时只是pause貌似不行，后台似乎还在继续下载，所以会报很多NetworkError。改了下，应该只会包一个错了。
然后是出错三次以后播放下一首。网络环境恶劣的忧心...
> 网络出错三次以后播放下一首

- src/main.py
- src/widgets/lyric.py
- src/widgets/notify.py
when more than 1 screen exist, move window to primary screen center
> support multi screen

- src/controllers.py
- src/views.py
when mainWindow closed, quit application
> bugfix: #62

- src/base/player.py
- src/widgets/lyric.py
refresh lyric every 0.1 second
> optimize lyric window

- feeluown/plugins/neteasemusic/model.py
- feeluown/plugins/neteasemusic/nem.py
Error log:
File "./feeluown/plugins/neteasemusic/nem.py", line 179, in search_net
songs = NSongModel.search(text)
File "./feeluown/plugins/neteasemusic/model.py", line 156, in search
if data['result']['songCount']:
KeyError: 'result'
> fix coredump when searching netease with empty string

- feeluown/consts.py
I don't feel it is right and not sure which one you prefer. Maybe I was wrong that you kept these two on purpose?
> 移除一个DEFAULT_THEME_NAME

- feeluown/components/volume_button.py
- feeluown/ui.py
Thank you for this fantastic repo. I tried to add a volume slider and now it works well on my PC(Arch Linux).  Please check if the code meets your requirements or if there are bugs. Note the code hasn't been tested on Mac OS, since I don't have one.
I left the volume icons to further improvements because it's hard to handle. It may be better to separate the theme and the ui components and provide a theme system.
> add volume slider

- Makefile
- feeluown/widgets/collection_toc.py
目标：
milestone：
- 可能的难点：歌手图标（参考专辑）；文字布局；文字上嵌入链接
- 可能的难点：专辑/歌手的 uri 表示
- 可能的难点：nonblocking；UI 布局
> WIP: collection enhancement

- setup.cfg
- setup.py
Includes README.md as long description.
> config: refine setup.py

- feeluown/player.py
增加feeluown.Playlist.Playlist  对 FM mode的支持
> add FM mode

- feeluown/player.py
- fuocore/playlist.py
- tests/feeluown/test_player.py
1. 加了一点文档和测试
2. 两个修改
1. 之前，在修改 mode 为 fm 的时候，没有设置 playback_mode -> 改成了，修改 mode 为 fm 的时候，自动设置 playback_mode 为 sequential
2. 简化了一下 playlist.next 的实现
cc @wuliaotc
> docs,tests: add docs and test for fm mode

- fuocore/cmds/playlist.py
- fuocore/cmds/show.py
- fuocore/utils.py
> bugfix: fuo add playlist doesn't work

- mpv.py
Fixes 322#
Signed-off-by: XuChe <chrisxuche@gmail.com>
> feat: Try to load mpv-1.dll from MPV_DLL_PATH(if set) and PATH.

- mpv.py
This reverts commit caa160f02048b0687bed0c321aba10ea911e2510.
https://travis-ci.com/feeluown/FeelUOwn/jobs/284709694
> Revert "feat: use newest mpv.py"

- feeluown/containers/right_panel.py
- fuocore/models/__init__.py
- fuocore/models/uri.py
- tests/feeluown/test_collection.py
1. support pure albums collection display
2. change artists_name styles(change 'a,b,c' to 'a, b & c', more normal expression)
3. add rec_songs & rec_playlists fields for user model
> slight changes

- feeluown/fm.py
- feeluown/player.py
- tests/feeluown/test_fm.py
之前，这样的操作顺序，会导致无法再次进入 fm 模式
1. 激活 fm 模式
2. 播放其它歌曲若干首
3. 再次激活 fm 模式（会失败，并且无法再次激活，日志会显示 already activated，但实际上并没有）
目前加了一个单元测试来覆盖这个场景
> bugfix: can't activate fm mode after playing other songs

- feeluown/app.py
- feeluown/cli.py
- feeluown/entry_points/base.py
- feeluown/global_hotkey_mac.py
- feeluown/server.py
- fuocore/pubsub.py
- fuocore/utils.py
call `app.get_listen_addr()` for get a proper listen address
> add config ALLOW_LAN_CONNECT

- feeluown/ui.py
- fuocore/media.py
- fuocore/mpvplayer.py
- tests/test_media.py
- tests/test_player.py
一个改动：在 app 启动时会初始化一些 OpenGLWidget 的一些设置，这个不知道在 Linux 下是否能正常运行。
> feat: play song whose media is a video

- feeluown/app.py
- feeluown/compat.py
- feeluown/entry_points/run.py
- feeluown/patch.py
- setup.py
more details: https://github.com/feeluown/FeelUOwn/issues/346
> bugfix: use qasync/quamash for different python version

- .travis.yml
- feeluown/linux/__init__.py
related issue: https://github.com/feeluown/FeelUOwn/commit/c4095f1e0f26a7aabe2d3ca3373e157bc7ea7db3#r37696368
> WIP: add integration test for mpris2

- feeluown/browser.py
- feeluown/containers/right_panel.py
- feeluown/containers/table.py
- feeluown/gui/pages/search.py
- feeluown/helpers.py
- feeluown/widgets/album.py
- feeluown/widgets/artist.py
- feeluown/widgets/imglist.py
- feeluown/widgets/magicbox.py
- feeluown/widgets/meta.py
- feeluown/widgets/playlist.py
- feeluown/widgets/tabbar.py
- feeluown/widgets/table_toolbar.py
- fuocore/library.py
- setup.py
> *: some features for 3.4.1

- research/mpv_qtwidget_opengl.py
get fullpath of webm file making this research script more friendly for newbee
> get fullpath of webm file 

- fuocore/serializers/plain.py
> Don't append empty string to text_list

- feeluown/gui/video_show.py
- feeluown/ui.py
- feeluown/widgets/mpv_old.py
- fuocore/mpvplayer.py
- fuocore/utils.py
- mpv.py
- mpv_old.py
- research/mpv_qtwidget_opengl.py
- research/mpv_render.py
- setup.cfg
- setup.py
* use python-mpv 0.5.2
* use mpv new render context api
close https://github.com/feeluown/FeelUOwn/issues/432
有个尴尬的地方：ubuntu 18.04 libmpv 不支持新的 render context api，而 arch libmpv 是 0.33，已经抛弃了老的 opengl-cb api。
> player: use mpv new render context api

- feeluown/gui/helpers.py
- feeluown/gui/page_containers/table.py
Just don't create parent reference.
> Fix imglist memory leak

- feeluown/cli/install.py
目前的代码只能处理中文和英文系统的默认地址, 不能处理用户自定义的地址和其他语言地址.
> Linux 下在创建快捷方式时使用 xdg-user-dir 寻找桌面地址

- feeluown/rpc/cmds/playlist.py
This should fix this issue: https://github.com/feeluown/FeelUOwn/issues/491
> bugfix: error when rpc playlist add netease song

- .pylintrc
- feeluown/__init__.py
- feeluown/gui/pages/song_explore.py
- feeluown/library/flags.py
- feeluown/library/library.py
- feeluown/library/provider_v2.py
Provider example: https://github.com/feeluown/feeluown-netease/commit/a3d482db23a6b2d14dc1efda32ef9358e99198f2
> library: copy song web url in song explore page

- docs/source/quickstart.rst
The package is available in community.
> docs: update package information for Arch

- feeluown/app.py
- feeluown/collection.py
- feeluown/gui/helpers.py
- feeluown/gui/page_containers/table.py
- feeluown/gui/uimain/player_bar.py
- feeluown/gui/video_show.py
- feeluown/library/__init__.py
- feeluown/library/models.py
- feeluown/media.py
- feeluown/models/__init__.py
- feeluown/models/base.py
- feeluown/models/models.py
- feeluown/models/uri.py
- feeluown/player/__init__.py
- feeluown/player/mpvplayer.py
- feeluown/player/playlist.py
- feeluown/rpc/cmds/player.py
- feeluown/utils/sync.py
- tests/feeluown/test_fm.py
- tests/feeluown/test_serializers.py
> wip: Enhance video support

- Makefile
- feeluown/gui/widgets/labels.py
- feeluown/gui/widgets/progress_slider.py
- feeluown/player/base_player.py
- feeluown/player/mpvplayer.py
- tests/gui/widgets/test_progress_slider.py
- tests/gui/widgets/test_tabbar.py
> gui: prevent user to drag the slider when there is no media and show proper duration/position

- feeluown/gui/pages/model.py
- feeluown/library/__init__.py
- feeluown/library/library.py
- feeluown/library/models.py
- feeluown/library/provider_v2.py
- feeluown/models/uri.py
https://github.com/feeluown/FeelUOwn/issues/507
> library: help implement modelv2 more easier

- feeluown/utils/utils.py
- mpv.py
try to fix https://github.com/feeluown/FeelUOwn/issues/571
> *: try to be compatible with libmpv 2.0

- feeluown/server/dslv1/codegen.py
> Missing `f` prefix on f-strings fix

- feeluown/gui/uimain/player_bar.py
- feeluown/gui/widgets/cover_label.py
- feeluown/library/library.py
- feeluown/player/playlist.py
- tests/player/test_fm.py
- tests/player/test_playlist.py
> gui: show media artwork as possible

- docs/source/quickstart.rst
- feeluown/cli/install.py
fix macOS start path, doc genicon command
> fix(macOS): brew install doc, start path

- feeluown/library/library.py
- feeluown/library/model_protocol.py
- feeluown/library/provider_protocol.py
- feeluown/library/provider_v2.py
- tests/conftest.py
- tests/library/test_protocol.py
- tests/library/test_provider.py
Before, if a provider supports X, it should declare a flag in its meta. For exmple, when a provider supports song_get, the code looks like this
```python
class FakeProvider:
class meta:
flags = {ModelType.song: ProviderFlags.song_get}
def song_get(self, identifier):
return song
```
The better way is to use structural subtyping. After this PR, the provider do not need to declare the flags anymore, and it just need to implement SongGetProtocol. And SongGetProtocol looks like this
```python
@runtime_checkable                                                                                                                                                                                                                          
class SupportsSongGet(Protocol): …
```
> library: use interface(protocol) to check if a provider supports X

- feeluown/app/gui_app.py
- feeluown/gui/ui.py
- feeluown/gui/uimain/toolbar.py
- feeluown/gui/widgets/messageline.py
Show notification  on the bottom message line.
Also,  https://github.com/feeluown/FeelUOwn/issues/590 should be fixed.
fix #590
> gui: add notification message box(line)

- feeluown/library/provider_v2.py
> [bilibili plugin] implement playlist v2

- feeluown/gui/uimain/player_bar.py
- feeluown/gui/video_show.py
- feeluown/utils/dispatch.py
fix https://github.com/feeluown/FeelUOwn/issues/608
> gui: watch video continuously

- feeluown/player/playlist.py
- tests/player/test_playlist.py
> player: cover maybe a media object

- feeluown/local/db.py
- feeluown/local/provider.py
* 歌手封面自适应选择
* 歌手默认专辑按照发布时间降序排列，歌手歌曲按照标题升序排列
> * 歌手信息统计增强

- .pylintrc
- feeluown/gui/assets/themes/common.qss
- feeluown/gui/base_renderer.py
- feeluown/gui/helpers.py
- feeluown/gui/page_containers/scroll_area.py
- feeluown/gui/page_containers/table.py
- feeluown/gui/pages/search.py
- feeluown/gui/uimain/page_view.py
- feeluown/gui/widgets/accordion.py
- feeluown/gui/widgets/header.py
- feeluown/gui/widgets/songs.py
> gui: new search page

- feeluown/gui/helpers.py
- feeluown/gui/uimain/page_view.py
- feeluown/gui/widgets/album.py
> gui: album/artist view can't scroll sometimes

- feeluown/app/gui_app.py
- feeluown/entry_points/run_app.py
1. use Segoe UI Symbol / Microsoft Yahei fonts 
2. support hidpi
> gui: make it looking good on Windows

- .pylintrc
- feeluown/gui/pages/song_explore.py
- feeluown/gui/ui.py
- feeluown/gui/widgets/separator.py
- feeluown/local/provider.py
> gui: redesign 'song explore' page

- Makefile
- feeluown/gui/helpers.py
- feeluown/gui/widgets/album.py
- feeluown/gui/widgets/comment_list.py
- feeluown/gui/widgets/frameless.py
- feeluown/gui/widgets/imglist.py
- feeluown/gui/widgets/login.py
- feeluown/gui/widgets/magicbox.py
- feeluown/gui/widgets/meta.py
- feeluown/gui/widgets/mpv.py
- feeluown/gui/widgets/playlists.py
- feeluown/gui/widgets/progress_slider.py
- feeluown/gui/widgets/provider.py
- feeluown/gui/widgets/song_minicard_list.py
- feeluown/gui/widgets/songs.py
- feeluown/gui/widgets/volume_button.py
- feeluown/gui/widgets/weblogin.py
fix  https://github.com/feeluown/FeelUOwn/issues/659
> *: add type check for feeluown.gui.widgets

- Makefile
- feeluown/app/gui_app.py
- feeluown/gui/uimain/playlist_overlay.py
- feeluown/gui/widgets/song_minicard_list.py
> gui: playlist view can scroll to the current song

- feeluown/nowplaying/common/__init__.py
fix #668
I'm not sure if the progress bar works well after this change.
> nowplaying: use seeked signal

- feeluown/gui/image.py
- feeluown/gui/page_containers/table.py
- feeluown/gui/widgets/cover_label.py
- feeluown/gui/widgets/imglist.py
- feeluown/gui/widgets/meta.py
> gui: render the album cover more clearly and allow user to download the image

- feeluown/nowplaying/linux/mpris2.py
> nowplaying: minor enhancement of mpris2 integration

- feeluown/nowplaying/linux/mpris2.py
Set trackid to make Seek method work.
```
May 14 11:14:58 arch plasmashell[711]: QDBusConnection: error: could not send message to service "org.mpris.MediaPlayer2.feeluown" path "/org/mpris/MediaPlayer2" interface "org.mpris.MediaPlayer2.Player" member "SetPosition": Marshalling failed: Invalid object path passed in arguments
```
> [fix](nowplaying) fix mpris2 seek method

- feeluown/gui/uimain/lyric.py
Learned from lyricX and [waylyrics](https://github.com/poly000/waylyrics).
> gui: auto resize lyric window

- feeluown/excs.py
- feeluown/gui/page_containers/table.py
- feeluown/gui/pages/model.py
- feeluown/gui/widgets/album.py
- feeluown/gui/widgets/imglist.py
- feeluown/library/library.py
- feeluown/library/models.py
- feeluown/library/provider_protocol.py
- library: add `song_count` field for AlbumModel and add SupportsAlbumSongsReader protocol
- gui: show released date on AlbumListView
> gui: show released date on AlbumListView

- feeluown/library/models.py
- feeluown/local/schemas.py
- feeluown/models/models.py
- feeluown/serializers/model_helpers.py
- setup.py
- tests/library/test_model_v2.py
This would fix https://github.com/feeluown/FeelUOwn/issues/715 in the sense that it builds against pydantic >= 2.
I'm trying to package it for https://archlinux.org/packages/extra/any/feeluown/ and this PR should address the packaging issue at least.
*Small note: I signed with my packager key, but used my github email, hence "Unverified"*
> Renamed __cache__ to _cache

- feeluown/entry_points/run.py
- feeluown/gui/uimain/lyric.py
- feeluown/library/models.py
- feeluown/utils/patch.py
- setup.py
- tests/library/test_model_v2.py
> library: compat with pydantic v1&v2

- feeluown/gui/uimain/lyric.py
fix https://github.com/feeluown/FeelUOwn/issues/733
> gui: lyric font dialog may cause app crash

- .github/workflows/build.yml
- .vscode/settings.json
- feeluown/app/config.py
- feeluown/app/server_app.py
- feeluown/webserver/__init__.py
- feeluown/webserver/server.py
- setup.py
> *: introduce webserver

- feeluown/excs.py
- feeluown/gui/helpers.py
- feeluown/gui/page_containers/table.py
- feeluown/gui/pages/song_explore.py
- feeluown/library/__init__.py
- feeluown/library/excs.py
- feeluown/library/library.py
- feeluown/library/provider.py
- feeluown/player/playlist.py
- feeluown/server/handlers/show.py
NotSupported is a low-level exception
> library: remove NotSupported exception

- feeluown/player/mpvplayer.py
> Fix drag-and-release on progressslider toggles play status

- feeluown/gui/uimain/lyric.py
- feeluown/player/lyric.py
> gui: show message when there is no available lyric

- feeluown/gui/widgets/songs.py
- feeluown/library/__init__.py
- feeluown/library/base.py
- feeluown/library/models.py
> gui: draw vip tag if a song needs vip privilege

- feeluown/gui/uimain/lyric.py
> gui: lyric-window should not be moved when dragging sizegrip

- feeluown/gui/widgets/img_card_list.py
- feeluown/library/models.py
- feeluown/utils/utils.py
> *: show playlist play_count

- feeluown/app/gui_app.py
- feeluown/entry_points/run_app.py
- feeluown/gui/helpers.py
- feeluown/gui/pages/search.py
- feeluown/gui/pages/template.py
- feeluown/gui/widgets/labels.py
1. remember search settings (search from which providers)
2. show search performance
> gui: enhance search page

- .github/workflows/build.yml
- .github/workflows/macos-release.yml
> ci: try to fix macos CI
