feeluown/plugin/NetEaseMusic/normalize.py

点击一个没有被缓存过的歌单会导致程序崩溃，错误信息如下：
```
File "../feeluown/view_api.py", line 199, in on_playlist_btn_clicked
pid, cache=False)
File "../feeluown/plugin/NetEaseMusic/normalize.py", line 182, in get_playlist_detail
return self.update_playlist_detail(pid)
File "../feeluown/plugin/NetEaseMusic/normalize.py", line 161, in update_playlist_detail
if PlaylistDb.exists(pid):
File "../feeluown/plugin/NetEaseMusic/model.py", line 42, in exists
if ControllerApi.session.query(cls).filter(cls.pid==pid).count() > 0:
File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2955, in count
return self.from_self(col).scalar()
File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2724, in scalar
ret = self.one()
File …
```

Avoid calling `update_playlist_detail` twice in `NetEaseAPI.get_playlist_detail`

---

feeluown/app.py
feeluown/request.py

当断网的情况下打开 `FeelUOwn`，窗口下方显示 `网络连接错误`; 此时连接网络进行登录，窗口下方仍然显示 `网络连接错误`，而不会消失。
经过调试知道，打开断网的情况下，`Request` 的 `get` 方法调用的 `self._app.message()` 方法下，`get_event_loop` 失败。
```python
def get_event_loop(self):
"""Get the event loop.
This may be None or an instance of EventLoop.
"""
if (self._local._loop is None and
not self._local._set_called and
isinstance(threading.current_thread(), threading._MainThread)):
self.set_event_loop(self.new_event_loop())
if self._local._loop is None:
raise RuntimeError('There is no current event loop in thread %r.'
% threading.current_thread().name)
return self._local._loop
```
原因在于Request.get抛出异常的情况下，当前的线程不是`threading._MainThread`，导致 `get_event_loop` 调用失败。
`MessageLabel` 类的 `show_message` 用到了 `asyncio` 和 `消息队列`，主要实现异步显示消息文本，并且每个消息的显示滞留时间是 `3 秒`，最后队列为空，即没有任何消息要显示，则隐藏 …

fix network state bug

---

feeluown/__main__.py

[PEP 328 Relative Imports and __name__](https://www.python.org/dev/peps/pep-0328/#relative-imports-and-name)  ，相对导入在 package 分层中，使用模块的__name__ 属性得到模块的位置。但是如果模块的名字没有包含任何 package 信息（例如，__main__模块），相对导入会被当作顶层模块导入（a top level module），不管是否该模块实际位于文件系统。
根据 [6.4.2. Intra-package References](https://docs.python.org/3/tutorial/modules.html#intra-package-references) 的建议：
> Note that relative imports are based on the name of the current module.  Since the name of the main module is always "__main__", modules intended for use as the main module of a Python application must always use absolute imports.
__mian__ 使用 `绝对导入` 方式，而其他模块仍使用 `相对导入`
参考 [stackoverflow](http://stackoverflow.com/questions/16981921/relative-imports-in-python-3)  **vaultah** 的回答
[PEP 328 Rationale for Relative Imports] ，相对导入可以对大型的 …

fix: __main__ module can't use Relative Imports

---

feeluown/app.py
feeluown/ui.py

由于 volume slider 在 MacOS 中表现异常，所以去掉。
slider 处于 pc_panel 的最右边，显示不完整（设置 QSizePolicy 时，有可能不处于水平位置）
很遗憾竟然没图

Remove volume slider

---

docs/source/coding_style.rst
feeluown/player.py
feeluown/ui.py
fuocore/__init__.py
fuocore/media.py
fuocore/models.py
fuocore/mpvplayer.py
fuocore/player.py
tests/test_model.py
tests/test_player.py

A song can associate with multiple **`media`**, when the player play a song, the player can choose a media by policy set by user(temporarily not implemented). We use the policy(`hd><`) by default. 
**breakchange**
- rewrite the `fuocore.models.Media class` and rename as `fuocore.media.Media`. The old version fuo-netease should be broken.

feat: song mutliple quality support

---

feeluown/ui.py
feeluown/widgets/songs_table.py

修复以下两种情况的客户端闪退：
1. 没有歌曲时点击下方的mv按钮，报错：
```
[2019-08-15 10:25:47,758 WARNING model_parser] : invalid model url
File "/Users/hejl/JianGuo/FeelUOwn/feeluown/ui.py", line 519, in _play_mv
mv = song.mv
AttributeError: 'NoneType' object has no attribute 'mv'
[1]    84428 abort      fuo
```
2. 在客户端的播放列表界面中，有正在播放的歌曲时，通过fuo clear命令删除歌曲列表:
```
[2019-08-15 10:32:58,304 WARNING model_parser] : invalid model url
File "/Users/hejl/JianGuo/FeelUOwn/feeluown/widgets/songs_table.py", line 85, in flags
if song.exists == ModelExistence.no or \
AttributeError: 'NoneType' object has no attribute 'exists'
[1]    84580 abort      fuo
```

fix app crash

---

fuocore/mpvplayer.py

修bug，当没有歌曲播放时，拖动进度条导致app会crash
```
(fuo)  ✘ hejl@hejldeIMAC  ~/JianGuo/FeelUOwn   master  fuo -ns
/usr/local/lib/python3.7/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
File "/Users/hejl/JianGuo/FeelUOwn/feeluown/containers/player_control_panel.py", line 146, in <lambda>
lambda value: setattr(player, 'position', value))
File "/Users/hejl/JianGuo/FeelUOwn/fuocore/mpvplayer.py", line 179, in position
self._mpv.seek(position, reference='absolute')
File "/Users/hejl/JianGuo/FeelUOwn/mpv.py", line 649, in seek
self.command('seek', amount, reference, …
```

fix a crash bug

---

fuocore/serializers/__init__.py
fuocore/serializers/_plain_formatter.py
fuocore/serializers/base.py
fuocore/serializers/json.py
fuocore/serializers/json_.py
fuocore/serializers/model_helpers.py
fuocore/serializers/plain.py
fuocore/serializers/python.py
setup.py

**Usage**
```python
from fuocore.serializers import serialize
song = ...
print(serialize('json', song))
```
**简介**
这个 PR 是 json-output 的第三个 PR。
个人认为第一个 PR 存在的问题有两个
1. serializer 相关逻辑和 model 放在一起，理论上感觉分开比较好
2. model.to_dict 和 serializer 这两层可以合并
个人认为第二个 PR 存在的问题有一个
1. serializer 和 dumper 逻辑重复
**其它**
1. 这个 PR 只实现了 serializers，需要配合第一个 PR 的一些逻辑才能真正工作
2. 这个 PR 的性能比第二个似乎差一些，serialize 4k 首歌，大概 0.23s 左右，第二个 PR 0.15s 左右，第一个 PR 没缓存时 0.3s 左右，有缓存时 0.13s 左右

feat: add serializers for model

---

fuocore/cmds/__init__.py
fuocore/cmds/excs.py
fuocore/cmds/playlist.py
fuocore/cmds/show.py
fuocore/router.py
fuocore/utils.py
tests/test_cmds.py

通过这个 PR https://github.com/feeluown/FeelUOwn/pull/380 ，发现以前设计的一些不科学的地方
1. 处理 CmdException，而不是简单的抛出 internal server error
2. 给 show 命令添加一些单测
2. 去除一些重复代码

Cmds refactor

---

feeluown/linux/mpris2.py

Fixes mpris2 status not updating for local source, since its being none is very common.
```
[2020-10-13 01:46:37,224 DEBUG __init__] : Registering callback <function _chain_future.<locals>._call_check_cancel at 0x7f52be075e50> to be invoked with arguments (<Future finished exception=TypeError('Don\'t know which D-Bus type to use to encode type "NoneType"') cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.8/asyncio/futures.py:360]>,) after 0 second(s)
```

Fix mpris:artUrl as None breaks the dbus encoding

---

feeluown/browser.py

The warning suggests to use path instead of uri, but if only path is specified (without a query), the following exception would be raised:
```
File "/usr/lib/python3.8/site-packages/feeluown/browser.py", line 54, in goto
self._goto(model, uri)
File "/usr/lib/python3.8/site-packages/feeluown/browser.py", line 88, in _goto
model = resolve(uri)
File "/usr/lib/python3.8/site-packages/fuocore/models/uri.py", line 145, in resolve
model, path = parse_line(line)
File "/usr/lib/python3.8/site-packages/fuocore/models/uri.py", line 110, in parse_line
line = line.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
This change fixes this behavior, and also updated the docstring accordingly.

Fix goto() with only path

---

feeluown/containers/player_control_panel.py

- Long song title (longer than song_title_label 's width) will scroll when cursor is on it.
- Fix some small problems caused by long song title, such as window will be stretched a little wider when change to a song with long name.
- Increase the width of position_label and duration_label to make them can be fully displayed.

[Feature & Fix] Make song title rolling if it's too long

---

feeluown/app.py
feeluown/containers/left_panel.py
feeluown/gui/browser.py
feeluown/gui/pages/__init__.py
feeluown/gui/pages/model.py
feeluown/gui/pages/search.py
feeluown/gui/ui.py
feeluown/models/uri.py
feeluown/widgets/magicbox.py
tests/feeluown/gui/test_browser.py

之前，browser 渲染 model 走的不是 route/dispatch 这一套统一的逻辑，这给维护和扩展带来了许多额外成本。
在这个 PR 里面，我们做了如下几件事情
以后的可以进一步优化：
1. 将 model 的展示逻辑从 table container 中移动到 page/model 中来。不过这个事情不急
另外，也有一些正在思考的点：
1. browser 是对外提供一个 `goto` 接口，还是对外提供 `goto_model_page` 以及 `goto_page` 两个接口 🤔

gui: add page/model

---

feeluown/fuoexec.py

There is a small typo in feeluown/fuoexec.py.
Should read `signal` rather than `siganl`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, siganl -> signal

---

feeluown/library/library.py
feeluown/player/base_player.py
feeluown/player/player.py
feeluown/player/playlist.py
feeluown/widgets/songs.py
tests/feeluown/test_player.py

当 prepare_media 函数出错时，会有许多 corner case
1. 如果下一首歌曲没有可用的 media，下面情形有可能死循环或程序崩溃
1. 用户点击了 next
2. 用户移除了当前歌曲

Fix player critical bug

---

feeluown/linux/mpris2.py

```
[2021-05-06 19:35:54,899 feeluown.task:83] [WARNING]: Task mpris2-update-property failed: unsupported operand type(s) for *: 'NoneType' and 'int'
[2021-05-06 19:35:54,899 feeluown.linux.mpris2:119] [ERROR]: mpris update song props failed
File "/usr/lib/python3.9/site-packages/feeluown/linux/mpris2.py", line 117, in cb
future.result()
File "/usr/lib/python3.9/site-packages/feeluown/task.py", line 81, in _cb
future.result()
File "/usr/lib/python3.9/site-packages/qasync/__init__.py", line 140, in run
r = callback(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/feeluown/linux/mpris2.py", line 138, in _update_song_props
'mpris:length': dbus.Int64(song.duration*1000),
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

Fix an error raised in mpris2.py when song.duration is None

---

feeluown/lyric/live_lyric.py

The warning is still there, but the error and traceback below are gone after this simple change.
```
[2021-05-06 06:07:23,363 feeluown.models.base:444] [WARNING]: Model KuwoLyricModel get return None
[2021-05-06 06:07:23,364 qasync._QEventLoop:696] [ERROR]: Exception in callback LiveLyric.on_song_changed.<locals>.cb(<Future finis...7fef244a79d0>>) at /usr/lib/python3.9/site-packages/feeluown/lyric/live_lyric.py:64
handle: <Handle LiveLyric.on_song_changed.<locals>.cb(<Future finis...7fef244a79d0>>) at /usr/lib/python3.9/site-packages/feeluown/lyric/live_lyric.py:64>
File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "/usr/lib/python3.9/site-packages/feeluown/lyric/live_lyric.py", line 70, in …
```

Silent an error when lyric is not present

---

feeluown/library/__init__.py
feeluown/library/library.py
feeluown/player/playlist.py
tests/conftest.py
tests/feeluown/test_playlist.py
tests/test_library.py

add a_list_song_standby_v2 API

---

feeluown/plugin.py
feeluown/version.py

pkg_resources is expensive to load, which takes more than 400ms here.
Let's use importlib.metadata from stdlib for Python 3.8+ for entry points,
and packaging.version for version parsing instead. It boosts start up
time significantly.
Some benchmark data:
On `fuo --help`, which involves the version parsing but not the entry
points:
Before: 0.908s
After: 0.398s
On `fuo search test` with an added "sys.exit(1)" clause right after
scanning the entry points:
Before: 0.991s
After: 0.502s

Avoid importing pkg_resources

---

setup.py

Add packaging to install_requires

---

docs/source/quickstart.rst

Fix the error when executing `brew install feeluown/feeluown/feeluown --with-battery`:

fix install error on macos

---

setup.cfg

```
/usr/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```

Fix a warning from setuptools

---

feeluown/local/__init__.py
feeluown/local/db.py
feeluown/local/provider.py

1. 简单修复本地音乐搜索功能完全失效的问题
2. 支持配置是否对本地音乐的专辑艺术家信息进行分隔
3. 支持配置对本地音乐的艺术家信息分隔符与不拆分艺术家的列表(参考poweramp)

artist splitter功能增强

---

Makefile
feeluown/gui/helpers.py
feeluown/utils/reader.py
tests/test_reader.py

gui: can't scroll down after click 'play all' button

---

feeluown/gui/pages/song_explore.py
tests/gui/pages/test_pages.py

When the song's album does not exist, the page rendering may fail. The exception ModelCannotUpgrade is not catched.

gui: render song exploring page correctly

---

feeluown/gui/widgets/messageline.py

Before, the message line widget show text in one line. When the line is too long, and the width becomes big.

gui: window becomes large unexpectedly

---

feeluown/gui/helpers.py
feeluown/gui/pages/song_explore.py
feeluown/library/__init__.py
feeluown/library/excs.py
feeluown/library/library.py
feeluown/library/models.py
feeluown/models/models.py
feeluown/player/playlist.py
tests/conftest.py
tests/gui/test_helpers.py
tests/player/test_playlist.py

Before the field pic_url is added, user needs to fetch a AlbumModel
to get the image url of the song, which means that there needs another
IO request. However, for almost every music providers, the pic url of the song
can be fetched in get_song_detail API. So one IO request can be saved
to fetch a image url of the song.

library: add pic_url field for SongModel

---

Makefile
feeluown/app/app.py
feeluown/app/cli_app.py
feeluown/app/gui_app.py
feeluown/entry_points/run_app.py
feeluown/gui/pages/song_explore.py
feeluown/gui/tips.py
feeluown/gui/ui.py
feeluown/gui/uimain/lyric.py
feeluown/gui/uimain/player_bar.py
feeluown/gui/widgets/lyric.py
feeluown/gui/widgets/magicbox.py
feeluown/gui/widgets/messageline.py
feeluown/player/__init__.py
feeluown/player/lyric.py
feeluown/utils/aio.py
feeluown/utils/utils.py
tests/player/test_live_lyric.py

1. support translated lyrics
2. save and restore lyric window settings, including font, bg, fg, geometry
3. auto-scoll lyric view

player,gui: much better lyrics support

---

feeluown/gui/widgets/comment_list.py

gui: fix incorrect height of CommentListView items

---

.github/workflows/build.yml
feeluown/nowplaying/__init__.py
feeluown/nowplaying/macos.py
feeluown/nowplaying/nowplaying.py
feeluown/player/base_player.py
feeluown/player/lyric.py
tests/helpers.py
tests/test_nowplaying.py

1. Listen to media_loaded signal and update nowplaying position property.
2. Fix race condition when signals are emitted at the same time in different thread.

nowplaying: fix race condition, add tests and comments

---

feeluown/app/app.py
feeluown/entry_points/run_app.py
feeluown/plugin.py
tests/app/conftest.py
tests/entry_points/test_run_app.py
tests/test_plugin.py

Before, it is hard for users to define config for plugins. Now, it's really simple. 
For example, if users want to set http_proxy for youtube music, just write the following line in the fuorc
```
config.ytmusic.HTTP_PROXY='http://127.0.0.1:7890'
```

[enhance](plugin) scan plugins(without enabling them) at the very first

---

feeluown/cli/install.py

When on a fresh install as a system library (usually via OS packaging), the following will happen:
```
anton@hotlap ~ $ feeluown genicon
Generate icon, then you can see app on desktop.
File "/usr/bin/feeluown", line 33, in <module>
sys.exit(load_entry_point('feeluown==3.8.12', 'console_scripts', 'feeluown')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/feeluown/entry_points/run.py", line 27, in run
return run_cli(args)
^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/feeluown/entry_points/run_cli.py", line 6, in run_cli
aio.run(climain(args))
File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File …
```

Fixed issue where the code assumes ~/.FeelUOwn/ exists when copying png files

---

feeluown/collection.py
feeluown/gui/components/collections.py
feeluown/gui/uimain/sidebar.py
feeluown/gui/widgets/__init__.py
feeluown/gui/widgets/selfpaint_btn.py
tests/test_collection.py

目标是为了实现类似 “稍后再听 / 想听 / 发现” 等功能

*: add a collection sys_pool

---

feeluown/local/db.py

It should be an `int` according to `SongModel`'s spec, but not converted accordingly. Breaks pydantic validation:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for SongModel
duration
Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=226533.87755102038, input_type=float]
```

local: fix duration format

---

docs/source/quickstart.rst

Update Arch Linux package URL in quickstart.rst

---

feeluown/gui/components/line_song.py
feeluown/gui/drawers.py
feeluown/gui/helpers.py
feeluown/gui/uimain/player_bar.py
feeluown/gui/widgets/cover_label.py
feeluown/library/models.py
feeluown/player/playlist.py
tests/player/test_playlist.py

1. stop the player immediately when user plays a song, so that user knows the action is handling
2. remove some misleading logs from the playlist module
3. fill the cover_label with random color when cover is not available

player: some improvements about the player

---

feeluown/gui/browser.py
feeluown/gui/drawers.py
feeluown/gui/pages/recommendation.py
feeluown/gui/pages/recommendation_daily_songs.py
feeluown/gui/pages/template.py
feeluown/gui/uimain/sidebar.py
feeluown/gui/widgets/__init__.py
feeluown/gui/widgets/header.py
feeluown/gui/widgets/selfpaint_btn.py
feeluown/library/provider_protocol.py

基本思路：为了“写最少的代码，实现最多的功能”，资源提供方尽量只提供数据，由 FeelUOwn 来实现 UI。这样的好处是尽可能复用代码；对“前后端分离”理论上也是有好处的。
对于“推荐页”这个功能，后续还有以下 TODO
最好还可以完善一下

gui: add recommendation page

---

feeluown/app/app.py
feeluown/app/config.py
feeluown/player/mpvplayer.py

feat: naive implementation of fade in-out

---

feeluown/gui/components/menu.py
feeluown/gui/page_containers/table.py
feeluown/gui/pages/model.py
feeluown/gui/pages/song_explore.py
feeluown/gui/uimain/page_view.py
feeluown/gui/widgets/playlists.py
feeluown/gui/widgets/songs.py
feeluown/library/library.py
feeluown/library/models.py
feeluown/player/lyric.py
feeluown/player/playlist.py
feeluown/serializers/model_helpers.py
tests/gui/pages/test_pages.py

library: remove compatibility code for model v1

---

Makefile
feeluown/collection.py
feeluown/gui/components/btns.py
feeluown/gui/components/collections.py
feeluown/gui/components/menu.py
feeluown/gui/drawers.py
feeluown/gui/pages/search.py
feeluown/gui/provider_ui.py
feeluown/gui/uimain/floating_box.py
feeluown/gui/uimain/page_view.py
feeluown/gui/widgets/cover_label.py
feeluown/library/__init__.py
feeluown/library/library.py
feeluown/library/models.py
feeluown/library/provider.py
feeluown/library/provider_protocol.py
feeluown/player/playlist.py
feeluown/server/handlers/base.py
setup.cfg
tests/library/test_model_v2.py

library: remove model protocol usage

---

feeluown/gui/helpers.py
feeluown/gui/ui.py
feeluown/gui/uimain/nowplaying_overlay.py
feeluown/gui/uimain/player_bar.py
feeluown/gui/widgets/accordion.py

1. click the accordion header can fold/unfold contents
2. click the cover label to show/hide nowplaying overlay (demo)

gui: introduce ClickableMixin

---

feeluown/gui/widgets/login.py

gui: login with keyring

---

feeluown/gui/tray.py
feeluown/gui/uimain/player_bar.py

**Summary**
When UI operations is done in non-mainthread, this warning is raised.
This PR fix this warning by moving operations to main-thread.
**Details**
After PLAYBACK_CROSSFADE is enabled, player.play/pause is called in non-main-thread during fading,
and some UI updates is supposed done when player state changed.

*: fix 'QObject::startTimer: Timers cannot be started from another thread'

---

feeluown/pyinstaller/main.py

Before, libmpv can not be found

bundle: fix macos bundler

---

feeluown/gui/drawers.py
feeluown/gui/uimain/player_bar.py
feeluown/gui/widgets/volume_button.py

The older volume slider has two problems
1. UX is not good
2. drag the slider causes the app hang. Worse, 
> 正在播放时拖动音量导致界面卡死，xorg 下几乎卡死整个 xserver，wayland 下留一个音量条始终在顶部，主界面被 kwin 标记为灰色，音乐正常播放
此时 htop 看到所有进程均分 100% CPU（大概是得谢谢 GIL），命令行 fuo status 会卡死
本次 Syu 的 log https://fars.ee/Ginq 包含 upgraded feeluown (4.0.1-1 -> 4.1-1) 
Now, introducing a self-painting slider to solve these problems.
User can use up/down or mouse to adjust the volume.

gui: brand new volume slider

---

feeluown/gui/uimain/nowplaying_overlay.py
feeluown/gui/widgets/video.py

1.  fix video-show on Linux(tested on wayland) (before, it may use mpv's widget to show videos)
2. fix the video-ctl-button color

gui: fix several bugs of video-show

---

Makefile

add the following lines in makefile can also decrease the pacakge size by about 30MB
```
+       # remove some useless dlls to decrease the package size
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5Network.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5Quick.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5Qml.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5QmlModels.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5WebSockets.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/Qt5DBus.dll
+       rm -rf dist/FeelUOwn/_internal/PyQt5/Qt5/bin/opengl32sw.dll
```

packaging: decrease the size by about 100MB (on macOS)

---

feeluown/app/config.py
feeluown/collection.py
feeluown/gui/browser.py
feeluown/gui/helpers.py
feeluown/gui/pages/homepage.py
feeluown/gui/uimain/page_view.py
feeluown/gui/uimain/sidebar.py
feeluown/gui/widgets/header.py
feeluown/library/__init__.py
feeluown/library/collection.py
feeluown/library/provider_protocol.py
feeluown/player/lyric.py
feeluown/utils/aio.py

1. Renderring daily recommended playlists/songs from all providers in homepage.
2. fix #821
Add this option to enable new homepage
```python
config.ENABLE_NEW_HOMEPAGE = True
```

gui: add page home

---

feeluown/mpv.py

pickup from upstream: https://github.com/jaseg/python-mpv/commit/d96eaf7e64f1063ae16f88abfaa14c2997b3291d

fix: loadfile for mpv v0.38.0, fix #823

---

feeluown/player/mpvplayer.py

from libmpv API changelog
> --- mpv 0.38.0 ---
> 2.3    - partially revert the changes from API version 1.27, remove libmpv as
the default VO and move it to the bottom of the auto-probing order.
This restores the prior behavior on all platforms other than macOS,
but still auto selects libmpv/cocoa-cb on macOS if it was built with
support for cocoa-cb.
so we should set libmpv as vo explicitly.

player:   can't render video properly with libmpv(0.38) on Linux

---

feeluown/gui/assets/themes/common.qss
feeluown/gui/browser.py
feeluown/gui/components/avatar.py
feeluown/gui/drawers.py
feeluown/gui/pages/homepage.py
feeluown/gui/pages/recommendation.py
feeluown/gui/pages/toplist.py
feeluown/gui/uimain/sidebar.py
feeluown/gui/uimain/toolbar.py
feeluown/library/provider_protocol.py

library: add protocol SupportsDiscoveryToplist

---

tests/test_collection.py

Python 3.12 treats the typo as an error now:
```
=================================== FAILURES ===================================
_____________________________ test_collection_load _____________________________
tmp_path = PosixPath('/tmp/pytest-of-builduser/pytest-0/test_collection_load0')
song = SongModel(meta=<feeluown.library.models.ModelMeta object at 0x7acaf2177c50>, identifier='0', source='fake', state=<Mod...on=600000, children=[], genre='', date='', track='1/1', disc='1/1', pic_url='', media_flags=<MediaFlags.not_sure: 128>)
mocker = <pytest_mock.plugin.MockerFixture object at 0x7acad8c98b60>
def test_collection_load(tmp_path, song, mocker): …
```

tests: fix test_collection.py for Python 3.12

---

feeluown/library/models.py
feeluown/plugin.py

1. ArtistModel: song_count, album_count, mv_count
2. PlaylistModel: created, updated, play_count
3. VideoModel: play_count, released

library: add more metadata fields for models

---

feeluown/fuoexec/signal_manager.py

Assume we have the following code in fuorc
```
when('app.ui.songs_table.about_to_show_menu', ask_ai_background, use_symbol=True)
```
Before, if user execute `fuo exec < ~/.fuorc` multiple times, when the signal is emitted, the slot will be invoked multiple times.

fuoexec:  allow reload fuorc to debug easily

---

.github/workflows/build.yml
.github/workflows/win-release.yml
docs/source/fuorc.rst
feeluown/app/app.py
feeluown/app/config.py
feeluown/library/library.py
feeluown/library/provider_protocol.py
feeluown/library/ytdl.py
feeluown/player/playlist.py
setup.py

To use this feature, you should 
1. instance yt-dlp `pip install yt-dlp`
2. setup config in `~/.fuorc`, for example
```python
config.YTDL_RULES = [{'name': 'match_source',
'pattern': 'ytmusic',
'http_proxy': 'http://127.0.0.1:7890'},]
```

library: use yt-dlp as a global standby-provider

---

feeluown/library/library.py
feeluown/player/playlist.py
feeluown/utils/aio.py
tests/player/test_playlist.py

Currently, the player play the media after metadata is fetched.
However, some provider (ytmusic)  cost much time in fetching metadata. 
So add a timeout to workaround this problem.

player: add timeout when fetching song metadata

---

feeluown/player/playlist.py
tests/player/test_playlist.py

Before, next_song returns no song when the following songs are bad. For example, the playlist has [valid_song1, valid_song2, bad_song1, bad_song2] and the current song is valid_song2. At the this time, next_song return None before. After this PR, next_song returns valid_song1.

player: fix next_song when the following songs are bad

---

feeluown/app/server_app.py

Before, when a user enables webserver and does not install sanic, the app just crashes.
Now, log a error message instead.

server: fix crash when any webserver dependency is not installed

---

feeluown/utils/reader.py

'播放全部' may fail due to
```
[2024-11-16 21:49:48,867 feeluown.task:85] [ERROR]: Task play-all failed
File "/Users/xxx/code/feeluown/feeluown/task.py", line 81, in _cb
future.result()
File "/Users/xxx/code/feeluown/.venv/lib/python3.11/site-packages/qasync/__init__.py", line 150, in run
r = callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 173, in readall
list(self)
File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 98, in __next__
return self._read_next()
^^^^^^^^^^^^^^^^^
File "/Users/xxx/code/feeluown/feeluown/utils/reader.py", line 192, in _read_next
obj = next(self._g)
^^^^^^^^^^^^^
ValueError: generator already executing
[2024-11-16 21:49:48,871 qasync._QEventLoop:739] …
```

[fix](reader): fix play-all may fail due to 'ValueError: generator already executing'

---

feeluown/app/config.py
feeluown/gui/helpers.py
feeluown/gui/pages/homepage.py
feeluown/gui/widgets/img_card_list.py
feeluown/gui/widgets/selfpaint_btn.py
feeluown/gui/widgets/song_minicard_list.py
feeluown/plugin.py

```python
config.ENABLE_NEW_HOMEPAGE = True
config.NEW_HOMEPAGE_SETTINGS = {
'contents': [
{'name': 'RecListDailySongs', 'provider': 'netease'},
{'name': 'RecListDailyPlaylists', 'provider': 'qqmusic'},
{'name': 'RecACollectionOfSongs', 'provider': 'qqmusic'},
]
},
```

[feat](gui): customizable homepage

---

feeluown/app/config.py
feeluown/config.py
feeluown/gui/theme.py
feeluown/library/uri.py
feeluown/library/ytdl.py
feeluown/player/metadata_assembler.py
feeluown/plugin.py
feeluown/task.py
feeluown/utils/utils.py
tests/test_config.py

- allow assign to undeclared config field
- reduce unused logs

[bugfix](*) several bugfix

---

.github/workflows/build.yml
feeluown/gui/components/player_playlist.py
feeluown/gui/uimain/playlist_overlay.py
feeluown/player/__init__.py
feeluown/player/fm.py
feeluown/player/playlist.py
feeluown/player/radio.py
tests/player/test_playlist.py

[feat](player) add new feature “自动续歌” and enhance "歌曲电台"

---

feeluown/gui/components/player_playlist.py
feeluown/player/playlist.py
feeluown/serializers/plain.py
feeluown/uimodels/my_music.py
feeluown/uimodels/playlist.py
feeluown/uimodels/provider.py
setup.cfg
tests/app/conftest.py
tests/app/test_app.py
tests/app/test_server_app.py
tests/entry_points/test_run_app.py
tests/gui/pages/test_pages.py
tests/gui/widgets/test_widgets.py
tests/library/test_model_v2.py
tests/player/test_playlist.py

1. It can't be removed when the current song is the last in FM mode.
2. pytest: less warnings

player: show warning when user removes the current song in some cases

---

feeluown/app/config.py
feeluown/gui/uimain/playlist_overlay.py
feeluown/gui/widgets/settings.py
feeluown/library/library.py
feeluown/library/similarity.py
feeluown/library/text2song.py
feeluown/player/__init__.py
feeluown/player/ai_radio.py
feeluown/player/playlist.py
feeluown/player/radio.py
tests/library/test_library.py
tests/library/test_similarity.py

[feat](*): AI based radio

---

feeluown/app/app.py
feeluown/app/config.py

经过一段时间的使用，发现之前 ytdl 这个东西属过度设计（想太多）。
ytdl 实际上只对 feeluown-ytmusic 有用，并且它的配置也很复杂，不如直接把这坨逻辑移到 ytmusic 中去实现。所以先默认关闭这个功能。

[misc](library): disable ytdl by default

---

.github/workflows/build.yml
.github/workflows/macos-release.yml
.github/workflows/win-release.yml
feeluown/ai.py
feeluown/app/app.py
feeluown/app/config.py
feeluown/gui/drawers.py
feeluown/gui/ui.py
feeluown/gui/uimain/ai_chat.py
feeluown/gui/uimain/sidebar.py
feeluown/gui/widgets/__init__.py
feeluown/gui/widgets/magicbox.py
feeluown/gui/widgets/selfpaint_btn.py
feeluown/library/ai_standby.py
feeluown/library/library.py
feeluown/library/similarity.py
feeluown/library/standby.py
feeluown/library/text2song.py
feeluown/player/ai_radio.py
feeluown/utils/aio.py
setup.py
tests/library/test_similarity.py
tests/library/test_standby.py

[feat](AI) add several AI related features

---

feeluown/alert.py
feeluown/app/app.py
feeluown/gui/components/search.py
feeluown/gui/widgets/labels.py
feeluown/gui/widgets/login.py
feeluown/library/library.py
feeluown/library/models.py
feeluown/player/playlist.py
feeluown/task.py

[enhance](*) introduce alert manager

---

feeluown/mpv.py

This small PR resolves the `threading` deprecation warnings:
```python
/Users/runner/work/FeelUOwn/FeelUOwn/feeluown/mpv.py:862: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
```
It also fixes a few typos I came across along the way in the relevant files.

*: resolve daemon warnings for threading methods

---

feeluown/gui/theme.py

When the system appearance changes (for example, from dark to light), the player control panel of FeelUOwn  does not change. This PR fixes the problem.

gui: fix auto changing theme

---

feeluown/gui/image.py
feeluown/player/mpvplayer.py
feeluown/player/playlist.py

Before, feeluown stops the MPV by playing a `''` file. The action causes the MPV to emit an EndFile event in the new version of libmpv. In the old version of libmpv, it does not emit any event. This change causes the bug. 
```
[v] bdmv/bluray: Opening
[v] file: Opening
[error] file: Cannot open file '': No such file or directory
[error] stream: Failed to open .
[v] cplayer: Opening failed or was aborted:
[v] cplayer: finished playback, loading failed (reason 4)
[v] stream_callback: Opening http://xxxx
```
Now, call `stop` method directly to stop the MPV instead of `play('')`

player: the player skipped a song unexpectedly
